# Generated by Django 4.1 on 2022-09-02 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0002_alter_projectuser_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectuser',
            name='ConfirmPassword',
        ),
    ]
